name: Learning GitHub Script
on:
  issues:
    types: [opened]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - name: Comment on new issue
      uses: actions/github-script@0.8.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
            github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "🎉 You've created this issue comment using GitHub Script!!!"
            })
    - name: Get Project ID (for Projects v2)
      if: contains(github.event.issue.labels.*.name, 'bug')
      id: get_project
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const result = await github.graphql(`
            query {
              user(login: "JanTopolewskiZSK") {
                projectsV2(first: 10) {
                  nodes {
                    number
                    title
                  }
                }
              }
            }
          `);
          console.log(result.user.projectsV2.nodes);

    - name: Add issue to the project
      if: contains(github.event.issue.labels.*.name, 'bug')
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const projectId = "${{ steps.get_project.outputs.result }}";
          const issueId = context.payload.issue.node_id;

          const mutation = `
            mutation($projectId: ID!, $issueId: ID!) {
              addProjectV2ItemById(input: {projectId: $projectId, contentId: $issueId}) {
                item {
                  id
                }
              }
            }
          `;

          const result = await github.graphql(mutation, {
            projectId,
            issueId
          });

          console.log("✅ Added issue to project:", result.addProjectV2ItemById.item.id);
